name: "Tests"
on:
  pull_request:
  push:
    branches:
      - '*'
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Setup Python
      uses: actions/setup-python@v5
      id: setup-python
      with:
        python-version: '3.12'
    - name: Cache pip downloads
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: pip-lint-${{ runner.os }}-${{ runner.arch }}-${{ steps.setup-python.outputs.python-version }}-${{ github.run_id }}
        restore-keys: pip-lint-${{ runner.os }}-${{ runner.arch }}-${{ steps.setup-python.outputs.python-version }}-
    - name: Run linters
      run: pipx run --python "$WORKFLOW_PYTHON" tox run -e lint
      env:
        WORKFLOW_PYTHON: '${{ steps.setup-python.outputs.python-path }}'
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        python: ['3.10', '3.11', '3.12']
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Setup Python
      uses: actions/setup-python@v5
      id: setup-python
      with:
        python-version: ${{ matrix.python }}
    - name: Cache pip downloads
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: pip-test-${{ runner.os }}-${{ runner.arch }}-${{ steps.setup-python.outputs.python-version }}-${{ github.run_id }}
        restore-keys: pip-test-${{ runner.os }}-${{ runner.arch }}-${{ steps.setup-python.outputs.python-version }}-
    - name: Run tests
      run: pipx run --python "$WORKFLOW_PYTHON" tox run -e py
      env:
        WORKFLOW_PYTHON: '${{ steps.setup-python.outputs.python-path }}'
